export const ERROR_CODES = {
  // 通用错误
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  
  // 邀请码相关错误
  INVITE_CODE_EXPIRED: 'INVITE_CODE_EXPIRED',
  INVITE_CODE_INVALID: 'INVITE_CODE_INVALID',
  INVITE_CODE_ALREADY_USED: 'INVITE_CODE_ALREADY_USED',
  INVITE_CODE_EXPIRE_TIME_PAST: 'INVITE_CODE_EXPIRE_TIME_PAST',
  INVITE_CODE_TOO_MANY: 'INVITE_CODE_TOO_MANY',
  INVITE_CODE_CREATE_FAILED: 'INVITE_CODE_CREATE_FAILED',
  INVITE_CODE_VERIFY_FAILED: 'INVITE_CODE_VERIFY_FAILED',
  INVITE_CODE_USE_FAILED: 'INVITE_CODE_USE_FAILED',
  
  // 团队相关错误
  TEAM_INVITES_FETCH_FAILED: 'TEAM_INVITES_FETCH_FAILED',
  
  // 元数据相关错误
  METADATA_INVALID_URL: 'METADATA_INVALID_URL',
  METADATA_PARSE_FAILED: 'METADATA_PARSE_FAILED',
  METADATA_REQUEST_TIMEOUT: 'METADATA_REQUEST_TIMEOUT',
  METADATA_CACHE_UNAVAILABLE: 'METADATA_CACHE_UNAVAILABLE',
  METADATA_MISSING_REQUIRED_FIELDS: 'METADATA_MISSING_REQUIRED_FIELDS',
  METADATA_INVALID_DATA: 'METADATA_INVALID_DATA',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];